x-bot-common: &bot-common
  build:
    context: .
    dockerfile: Dockerfile
  image: zhekop/wa-user-bot-v2-artdeko:main
  env_file:
    - .env
  environment:
    TZ: Europe/Moscow
services:
  api:
    <<: *bot-common
    working_dir: /app
    entrypoint: ["/app/wa-user-bot"]
    ports:
      - "5001:5001"
    volumes:
      - ./sessions:/app/sessions
      - ./data:/app/data
    restart: unless-stopped
  bot:
    <<: *bot-common
    working_dir: /admin-tg-bot
    entrypoint: ["python", "main.py"]
    environment:
      WHATSAPP_API_URL: "http://api:5001"
    volumes:
      - ./sessions:/admin-tg-bot/sessions
      - ./data:/admin-tg-bot/data
    depends_on:
      - api
    restart: unless-stopped