from .admin_kb import (
    account_detail_kb,
    accounts_list_kb,
    admin_cancel_kb,
    admins_list_kb,
    auth_cancel_kb,
    back_to_accounts_kb,
    main_menu_kb,
    communications_menu_kb,
    group_choose_accounts_kb,
    group_days_options_kb,
    group_detail_kb,
    group_time_options_kb,
    proxy_list_kb,
    proxy_detail_kb,
    proxy_cancel_kb,
    proxy_assign_list_kb,
)

__all__ = [
    "account_detail_kb",
    "accounts_list_kb",
    "admin_cancel_kb",
    "admins_list_kb",
    "auth_cancel_kb",
    "back_to_accounts_kb",
    "main_menu_kb",
    "communications_menu_kb",
    "group_choose_accounts_kb",
    "group_days_options_kb",
    "group_detail_kb",
    "group_time_options_kb",
    "proxy_list_kb",
    "proxy_detail_kb",
    "proxy_cancel_kb",
    "proxy_assign_list_kb",
]
